# Generated by Django 3.1.5 on 2021-04-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbon_fiber',
            old_name='processing',
            new_name='carbon_fiber_processing',
        ),
        migrations.RenameField(
            model_name='prepreg',
            old_name='processing',
            new_name='prepre_processing',
        ),
    ]
