# Generated by Django 3.1.5 on 2021-04-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_auto_20210417_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepreg',
            old_name='prepre_processing',
            new_name='prepreg_processing',
        ),
    ]
