# Generated by Django 3.1.5 on 2021-04-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_auto_20210417_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbon_fiber',
            name='carbon_fiber_name',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepreg',
            name='prepreg_name',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
