# Generated by Django 3.1.5 on 2021-04-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_auto_20210417_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carbon_Fiber',
            new_name='CarbonFiber',
        ),
        migrations.AlterField(
            model_name='prepreg',
            name='cure_temp',
            field=models.IntegerField(),
        ),
    ]
