# Generated by Django 3.1.5 on 2021-04-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_auto_20210422_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepreg',
            name='cure_temp',
            field=models.CharField(max_length=10),
        ),
    ]
